name: Feature request
description: Suggest an improvement to VMR.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: need
    attributes:
      label: User need
      description: What problem would this feature solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed behavior
      description: Describe how you expect the feature to work.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any workarounds or alternatives you considered.
